common: Fix qcacld-2.0 build fail with error 'a function declaration without a prototype'
Disable warning 'strict-prototypes' as error for clang-r510928 on Android 14.

error log:
  qcacld-2.0/CORE/HDD/src/wlan_hdd_main.c:21018:21: error: a function declaration
  without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]