MA-23736 refined evk_93/evk_943 SELinux rule.
Meet the below compile error under user build:
ERROR: permissive domains not allowed in user builds
List of invalid domains:
system_server

Swiftshader needs to create executable memory.
Remove the harmful workaround for system_server as we defined
PRODUCT_REQUIRES_INSECURE_EXECMEM_FOR_SWIFTSHADER := true

Change-Id: I7da30d4871d8e215c228f610591996ff599329c4
Signed-off-by: Jessie Hao <juan.hao@nxp.com>
Reviewed-on: http://androidsource.nxp.com/project/28678
Reviewed-by: Xuegang Liu <xuegang.liu@nxp.com>