MA-22231-1 change media.c2 process to aidl for watch_8ulp
Fix following build error:

The following HALs in device manifest are not declared in FCM <= level 202404:
  android.hardware.media.c2@1.0::IComponentStore/default
ERROR: files are incompatible: android.hardware.media.c2@1.0::IComponentStore/default
is deprecated in compatibility matrix at FCM Version 202404;

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Change-Id: I000eec00d4175a2be00cfcd7adf74f94d23cf9db
Reviewed-on: http://androidsource.nxp.com/project/24520
Reviewed-by: Xuegang Liu <xuegang.liu@nxp.com>