MA-22145-2 [Temp] Revert MA-21214 patch to pass build on Android15
Revert "MA-21214 fix the build error reported by bazel"
This reverts commit 38218f4676197c4dde42b2808d6e8267fc5062db.

Error log:
device/nxp/common/security/security.go:15:16:
undefined: allowlists.Bp2buildKeepExistingBuildFile

Signed-off-by: Richard Liu <xuegang.liu@nxp.com>
Change-Id: Ib8046d89a54b2ad09c3f2c6dacdea7fd0e5733f6